### ISSUE TITLE
Some issues [Resolved]

### ISSUE THREAD

**Issue by FrankX0** [scambo00/NodeRed-Honeywell-Lyric-API#1]
Playing around with this flow results in some errors.

### Device Access and Integration Flow
The JSON object is returned correctly.
The **Example for gobal object created from returned JSON data** however results in following error:
`"TypeError: Cannot read property 'changeableValues' of undefined"`

**Issue found**: `therm.settings.fan.changeableValues.mode` does not exist (in my case)

### Sample Flow for getting device data
Works correctly

### Sample Flow for setting device data
This results in two errors:
`"execute tStat CMD error: Cannot read property 'device_id' of undefined"` from **Define Globals / executeLyricTstatCMD**
`"No url specified"` from **Set Thermostat** (but probably caused by the first error)

**Issue found**: fix of the first issue resolves also this one.

**Comment by FrankX0** [comment]
One addition: the "Request every 15 min"  timer is actually set to 60 minutes.
This expiration time of the refresh token is actually 30 minutes.
So 15 minutes should be fine.

**Comment by scambo00** [comment]
FrankX0 
What thermostat do you have?

**Comment by FrankX0** [comment]
A Lyric T6

**Comment by FrankX0** [comment]
One additional issue.
The path used for storing the keys on a Raspberry Pi is not very convenient for me without root access: `/data/apiKey.log` and `/data/token.log`
I am using a relative path: `data/apiKey` and `/data/token.log`
They are therefore stored in the home folder.
