### ISSUE TITLE
Code 401, "Invalid or expired accesstoken"

### ISSUE THREAD

**Issue by FrankX0** [scambo00/NodeRed-Honeywell-Lyric-API#2]
The Lyric API worked great for a couple of months, but since a few weeks it stopped working and I'm getting an "Invalid or expired accesstoken".
After the initial request for the tokens it is working and I can read e.g. the current temperature.
But as soon as the the access token is refreshed for the first time, it results in the code 401.

The "Request Access Token" results in "Invalid grant".

Any ideas?

[Edit]
When the (initial) access token is requested, it returns both an access token but also a (new) refresh token.
The second request however still uses the original refresh token. Is this correct?

[Edit2]
Using the refresh token of the previous response resolves my issue.

**Comment by wscarangello** [comment]
Thanks you for resolving this issue.  I will add your change.  If you would like i can add you as a contributor.  I don't have much time for this and don't use it anymore.

**Comment by FrankX0** [comment]
Yes, please add me as contributor.
And thanks again for your work on this implementation.
