### ISSUE TITLE
no key files

### ISSUE THREAD

**Issue by lgwapnitsky** [scambo00/NodeRed-Honeywell-Lyric-API#4]
I just followed the instructions, and am getting the following errors:

Error: ENOENT: no such file or directory, open 'data/apiKey.log'

Error: ENOENT: no such file or directory, open 'data/token.log'

I retraced my steps, but still receive the errors

**Comment by scambo00** [comment]
Create the directory structure and files.  These files store your api key and token.

**Comment by lgwapnitsky** [comment]
Where do I create it? I'm rather new to node red

**Comment by FrankX0** [comment]
Normally it is in your home folder.
So if you are user  "pi", then the log files will be stored in `/home/pi/data`

**Comment by lgwapnitsky** [comment]
Got it, thanks!

**Comment by lgwapnitsky** [comment]
last question - what goes in each file?

*Larry G. Wapnitsky*


*E: Larry@Wapnitsky.com*
*Web: Larry.Wapnitsky.com <http://larry.wapnitsky.com/>Twitter:
@LGWapnitsky*

**Comment by lgwapnitsky** [comment]
nevermind.  they self-populated.

*Larry G. Wapnitsky*


*E: Larry@Wapnitsky.com*
*Web: Larry.Wapnitsky.com <http://larry.wapnitsky.com/>Twitter:
@LGWapnitsky*
